# Generated by Django 6.0.5 on 2026-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("facebook_user_id", models.CharField(max_length=120, unique=True)),
                ("reason", models.CharField(max_length=255)),
                ("violation_count", models.PositiveIntegerField(default=1)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("command_id", models.CharField(max_length=160, primary_key=True, serialize=False)),
                ("event_id", models.CharField(blank=True, max_length=160)),
                ("action", models.CharField(blank=True, max_length=60)),
                ("status", models.CharField(default="processing", max_length=30)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingError",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(blank=True, max_length=160)),
                ("command_id", models.CharField(blank=True, max_length=160)),
                ("topic", models.CharField(blank=True, max_length=120)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error_type", models.CharField(blank=True, max_length=120)),
                ("error_message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=160, unique=True)),
                ("event_type", models.CharField(max_length=40)),
                ("facebook_user_id", models.CharField(blank=True, max_length=120)),
                ("facebook_user_name", models.CharField(blank=True, max_length=255)),
                ("post_id", models.CharField(blank=True, max_length=120)),
                ("comment_id", models.CharField(blank=True, max_length=120)),
                ("message_id", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                ("intent", models.CharField(blank=True, max_length=60)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                ("action", models.CharField(blank=True, max_length=60)),
                ("status", models.CharField(default="received", max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_id"], name="application_event_i_f4cd39_idx"),
                    models.Index(fields=["comment_id"], name="application_comment_6c1b48_idx"),
                    models.Index(fields=["status"], name="application_status_a53eb7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FacebookRequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=255)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("retryable", models.BooleanField(default=False)),
                ("request_preview", models.TextField(blank=True)),
                ("response_preview", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["success", "created_at"], name="application_success_f6d042_idx")],
            },
        ),
    ]
