apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: '15s'
      queryTimeout: '60s'
      httpMethod: POST

  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    editable: false
    jsonData:
      database: 'fb_api-logs-*'
      timeField: '@timestamp'
      flavor: OpenSearch
      version: '2.11.0'
      logMessageField: message
      logLevelField: level
